### ISSUE TITLE
AppImage for download?

### ISSUE THREAD

**Issue by probonopd** [area-of-dev/Tor-Browser.AppImage#1]
Thanks for making this. Would you like to provide an automatically generated AppImage for download on GitHub Releases or are there reasons you want users to build their own?

**Comment by Kyther** [comment]
Seconding the request for a downloadable AppImage.  I attempted to build it and it failed on my system due to not being able to retrieve a CentOs zlib package.  (Trying on a second computer with the latest Mint got the same result.)  Could an AppImage be provided?  It would be greatly appreciated.

**Comment by AlexWoroschilow** [comment]
> Thanks for making this. Would you like to provide an automatically generated AppImage for download on GitHub Releases or are there reasons you want users to build their own?

that was the initial plan, but with the amount of the repositories i will reach the free github limit in a few days :). This is the main reason. 


> Seconding the request for a downloadable AppImage. I attempted to build it and it failed on my system due to not being able to retrieve a CentOs zlib package. (Trying on a second computer with the latest Mint got the same result.) Could an AppImage be provided? It would be greatly appreciated.

sure, will let you know when it is fixed.

**Comment by AlexWoroschilow** [comment]
@Kyther  fixed. You will need docker to build it. 
![image](https://user-images.githubusercontent.com/3255923/200691567-39187b43-6174-4c6e-88a3-96d2764dc07c.png)

@Kyther @probonopd 
Here you will find a ready to use appimage. It will be available in a few hours
https://apprepo.de/appimage/thorium
